### ISSUE TITLE
I Dare You to it

### ISSUE THREAD

**Issue by BBCByComcast** [TomJo2000/.dotfiles#4]
Do Not Give Up to My Project, That Why You Should _**Never Give Up to My Project**_ Instead

So You Should Do *No* Need Busy Anymore

## My Own Project

https://github.com/BBCByComcast/Windroid/

If That Case Then You Must Use My Project Instead

**Comment by TomJo2000** [comment]
I also have no interest in working on this, or any of your other projects.

***Cease and desist*** from contacting me again about it.
